version: "3.6"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
  # organizr: # replaced with Heimdall
  #   container_name: organizr
  #   restart: always
  #   image: lsiocommunity/organizr
  #   volumes:
  #     - ${USERDIR}/docker/organizr:/config
  #     - ${USERDIR}/docker/shared:/shared
  #   ports:
  #     - "9001:80"
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}      
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}      
      #- TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      #- USER=username #optional
      #- PASS=password #optional
    volumes:
      - ${USERDIR}/docker/transmission:/config
      - ${REMOTEDIR}/downloads/complete:/downloads
      - ${REMOTEDIR}/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped      
  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * THU" --cleanup # Check for updates every Thursday @ 4AM
  radarr:
    image: "linuxserver/radarr"
    container_name: "radarr"
    volumes:
      - ${USERDIR}/docker/radarr:/config
      - ${REMOTEDIR}/downloads/complete:/downloads
      - ${REMOTEDIR}/movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "7878:7878"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}    
  sonarr:
    image: "linuxserver/sonarr"
    container_name: "sonarr"
    volumes:
      - ${USERDIR}/docker/sonarr:/config
      - ${REMOTEDIR}/downloads/complete:/downloads
      - ${REMOTEDIR}/tvshows:/tv
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    ports:
        - "8989:8989"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}        
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
#      - UMASK_SET=022 #optional
    volumes:
     - ${USERDIR}/docker/plexms:/config
     - ${REMOTEDIR}/movies:/movies
     - ${REMOTEDIR}/tvshows:/tv
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
#      - RUN_OPTS=run options here #optional
    volumes:
      - ${USERDIR}/docker/sonarr:/config
      - ${REMOTEDIR}/downloads/complete:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
#      - UMASK_SET=022 #optional
    volumes:
      - ${USERDIR}/docker/bazarr:/config
      - ${REMOTEDIR}/movies:/movies
      - ${REMOTEDIR}/tvshows:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
#   code-server: # x86 only
#     image: linuxserver/code-server
#     container_name: code-server
#     environment:
#       - PUID=${PUID}
#       - PGID=${PGID}
#       - TZ=${TZ}
#       - PASSWORD=${WEBUI_PW} #optional
#       - SUDO_PASSWORD=${SUDO_PW} #optional
#     volumes:
#       - ${USERDIR}/docker/code-server:/config
#       - ${USERDIR}/docker/shared:/shared
#     ports:
#       - 8443:8443
#     restart: unless-stopped    
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
  netdata:
    image: netdata/netdata
    hostname: rpi2.local # set to fqdn of host
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro    